spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.190.135
    port: 5672
    username: admin
    password: admin  
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    
zuul:
  retryable: true

#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream








