spring:
  application:
    name: config-server
    
  profiles:
    active: native   
    
  rabbitmq:
    host: 192.168.190.135
    port: 5672
    username: admin
    password: admin   
    
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
 
  # config:
  #    git:
  #    uri: https://github.com/Donney01/sp_repo11  #仓库路径
  #   searchPaths: sp-config  #仓库下的一个字目录,里面存放的是配置文件
  #      username: your-username
  #      password: your-password
   
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh














